POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 111,
  "details": 123,
  "maximumAttendees": "5"
}

###

POST http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33/attendees
Content-Type: application/json

{
  "name": "Diego",
  "email": "diego@gmail.com"
}

###

GET http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33

###

GET http://localhost:3333/attendees/11/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33/attendees?query=diego